### ISSUE TITLE
Add Slovak National Gallery

### ISSUE THREAD

**Issue by mcudrnak** [Ambrosiani/museums-on-github#2]
Hi!

great list, can you please add 
https://github.com/SlovakNationalGallery

Thanks!

**Comment by Ambrosiani** [comment]
done! thanks for contributing to the list.

**Comment by mcudrnak** [comment]
that was quick, thanks!
nice blogpost btw, i went to mw2016 and hope that some collaboration will follow. IMA Lab is doing some impressive work with open source, in our lab at Slovak National Gallery we use similar tools which means possibility to develop projects where our needs overlap.
Do you know Dag Hensten from Nasjonalmuseet? He is doing the Samlingen web there, we will be collaborating for one project in coming months.

**Comment by Ambrosiani** [comment]
Yes, I like IMA's initiatives! I think it would be nice to breathe some life into [TourML](http://www.tourml.org) for instance. Lots of museum make tablet-first image views too, almost everyone starting from scratch.
